version: "3.8"
services:
  mlflow:
    build:
      context: ../..
      dockerfile: Dockerfile
    working_dir: /mlflow
    env_file:
      - .env
    environment:
      - PORT=5000
    ports:  
      - "5000:5000"
    depends_on:
      - mlflow-db
    volumes:
      - ../..:/mlflow
  mlflow-db:
    build:
      context: ./pg-docker
      dockerfile: Dockerfile.pg
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - ./pg-docker:/docker-entrypoint-initdb.d
      - mlflow-db:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:${DB_PORT}
volumes:
  mlflow-db:
